#!/usr/bin/env bash

cd $(dirname ${BASH_SOURCE[0]})

git fetch origin
reslog=$(git log HEAD..origin/master --oneline)
if [[ "${reslog}" != "" ]] ; then
  git merge origin/master # completing the pull
  echo "Changes found. Pulling changes..."
  systemctl restart decrypt.service
else
    echo "No changes found. Skipping."
fi
