#!/usr/bin/env bash

cd $(dirname ${BASH_SOURCE[0]})

git remote update

if [[ -n $(git status -uno -s) ]]; then
    echo "Changes found. Pulling changes..."
    git pull
    systemctl restart decrypt.service
else
    echo "No changes found. Skipping."
fi
